"""add_night_goal_to_preferences

Revision ID: 4e6a6e4e7d77
Revises: 5e41771729a4
Create Date: 2026-07-11 11:24:06.580209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e6a6e4e7d77'
down_revision: Union[str, Sequence[str], None] = '5e41771729a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('night_goal', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'night_goal')
    # ### end Alembic commands ###
