"""initial schema

Revision ID: fbf087413baf
Revises: 
Create Date: 2026-07-08 15:12:00.258116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf087413baf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_licenses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.String(length=10), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('author_name', sa.Text(), nullable=True),
    sa.Column('license_name', sa.Text(), nullable=False),
    sa.Column('license_url', sa.Text(), nullable=True),
    sa.Column('attribution_required', sa.Boolean(), nullable=False),
    sa.Column('attribution_text', sa.Text(), nullable=True),
    sa.Column('commercial_use_allowed', sa.Boolean(), nullable=False),
    sa.Column('derivative_allowed', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("asset_type IN ('audio','image','video')", name='ck_license_asset_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_licenses_asset_id'), 'asset_licenses', ['asset_id'], unique=False)
    op.create_table('image_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('cdn_url', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('visual_tags', sa.JSON(), nullable=False),
    sa.Column('spiritual_axis', sa.JSON(), nullable=False),
    sa.Column('visual_mood', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spiritual_journeys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('spiritual_axis', sa.String(length=20), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("level IN ('beginner','intermediate','advanced')", name='ck_journey_level'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('content_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('spiritual_axis', sa.JSON(), nullable=False),
    sa.Column('mood_tags', sa.JSON(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=False),
    sa.Column('sleep_safe', sa.Boolean(), nullable=False),
    sa.Column('meditation_safe', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cover_image_id', sa.String(length=36), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("type IN ('music','meditation','soundscape','binaural','breathing')", name='ck_content_type'),
    sa.ForeignKeyConstraint(['cover_image_id'], ['image_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_journey_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('journey_id', sa.String(length=36), nullable=False),
    sa.Column('current_day', sa.Integer(), nullable=False),
    sa.Column('completed_days', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['spiritual_journeys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'journey_id', name='uq_user_journey')
    )
    op.create_index(op.f('ix_user_journey_progress_user_id'), 'user_journey_progress', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('primary_goal', sa.String(length=20), nullable=False),
    sa.Column('preferred_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('preferred_content', sa.JSON(), nullable=False),
    sa.Column('spiritual_axis', sa.JSON(), nullable=False),
    sa.Column('experience_level', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('audio_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content_item_id', sa.String(length=36), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('cdn_url', sa.Text(), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('loudness_lufs', sa.Numeric(), nullable=True),
    sa.Column('bpm', sa.Numeric(), nullable=True),
    sa.Column('is_loopable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('binaural_params',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content_item_id', sa.String(length=36), nullable=False),
    sa.Column('left_hz', sa.Float(), nullable=False),
    sa.Column('right_hz', sa.Float(), nullable=False),
    sa.Column('beat_hz', sa.Float(), nullable=False),
    sa.Column('base_noise', sa.String(length=10), nullable=False),
    sa.Column('ambience', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_item_id')
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content_item_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'content_item_id')
    )
    op.create_table('journey_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('journey_id', sa.String(length=36), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content_item_id', sa.String(length=36), nullable=True),
    sa.Column('image_asset_id', sa.String(length=36), nullable=True),
    sa.Column('contemplation_text', sa.Text(), nullable=True),
    sa.Column('breathing_pattern', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['image_asset_id'], ['image_assets.id'], ),
    sa.ForeignKeyConstraint(['journey_id'], ['spiritual_journeys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journey_id', 'day_number', name='uq_journey_day')
    )
    op.create_table('playback_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content_item_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seconds_played', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playback_history_user_id'), 'playback_history', ['user_id'], unique=False)
    op.create_table('playlist_items',
    sa.Column('playlist_id', sa.String(length=36), nullable=False),
    sa.Column('content_item_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'content_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_items')
    op.drop_index(op.f('ix_playback_history_user_id'), table_name='playback_history')
    op.drop_table('playback_history')
    op.drop_table('journey_steps')
    op.drop_table('favorites')
    op.drop_table('binaural_params')
    op.drop_table('audio_assets')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_journey_progress_user_id'), table_name='user_journey_progress')
    op.drop_table('user_journey_progress')
    op.drop_table('content_items')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('spiritual_journeys')
    op.drop_table('playlists')
    op.drop_table('image_assets')
    op.drop_index(op.f('ix_asset_licenses_asset_id'), table_name='asset_licenses')
    op.drop_table('asset_licenses')
    # ### end Alembic commands ###
